apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-storage

commonLabels:
  app: ceph-exporter

resources:
- deployment.yaml
- service.yaml
- servicemonitor.yaml

configurations:
  - transformers/commonLabels.yaml
