apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ceph-exporter
spec:
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 5m

      relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
        - service
        targetLabel: instance
